services:
  - docker

env:
  global:
    - DOCKER_USERNAME=bogdandm
    - secure: "qI27/l47XQNw3fz0mX1FCtqvA3ZtFMH98XrD2wfu0IW92xEkdiMrb6h8QmtBPG6QFXkBs0h0R3wNq4suB6mBn38EJt/ohBHltjRlk9TLL7gcBkvm8U8tV2qXwbPNoeGqTHgPLImvmrtsYLrFJCnc88IJ/pDpuJRWa5a4T6sOzgmoXfjP4tMglmGbquKQQ1M2oFZ+DcPHau5+1P2G0yIuOD899LkHwwq8JUChVnl7UUx/AheMSX2ZFhrh4njn/0eya7I33C7PWEqcOZ5uYK2ycNlMnpWFYNdCDveuge3nlAvXg6Wq2NRTbJmOi0Kon6qd6CtSmsZHX9IxAEZTls12S7g2uRyZ5M1Xpmff89mjrQ1Rnblel6BqEhc05gNwLeMg/N7gqLp/LO7L5KrWUh8ehHlNn1j3ixxuLErnzchhoNeJQ3eFRSddgdOy8K+SDl3Y7pbpRfojV4TdTAbVDRzoDyRS1nwrYgUET7sQxd1oBb784MPrqkQFS52yTKrMulTKXszy6jPv8Q7YixpFpKwBvcDGGQC154fqR+XUlgUJSSZMzUtLEcon9Yevn9j2rXfwkxkoLMEN0CRTkME2QVJA2Rbey62t39CQwaCwebZN+QeNU9hsPtEKkPU5Choeu4dl6SIi5W3gL6NVA7QbJ4EyUefN5xu34abRJWqrGKbTrMQ="

install:
  - cd tests_online_docker
  - docker-compose build

script:
  - docker-compose up -d
  - sleep 10
  - docker exec tests-online-django bash -c "cd tests_online && ./manage.py test --no-input --parallel"

deploy:
  - provider: script
    script: bash docker_push.sh $TRAVIS_TAG
    on:
      tags: true
      all_branches: false