version: '3.7'

services:
  nginx:
    image: bogdandm/tests-online-nginx:latest
    build:
    ports:
      - "0.0.0.0:80:80"

  django:
    image: bogdandm/tests-online-django:latest
    build:

  django-migrate:
    image: bogdandm/tests-online-django:latest
    build:

  frontend:
    image: bogdandm/tests-online-frontend:latest
    build:
