version: '3.7'

services:
  nginx:
    image: bogdandm/tests-online-nginx:latest
    build:
      args:
        ROOT_CONF: nginx.conf
      cache_from:
        - bogdandm/tests-online-nginx:unstable
        - bogdandm/tests-online-nginx:latest

  django:
    image: bogdandm/tests-online-django:latest
    build:
      cache_from:
        - bogdandm/tests-online-django:unstable
        - bogdandm/tests-online-django:latest
    restart: unless-stopped

  frontend:
    image: bogdandm/tests-online-frontend:latest
    build:
      cache_from:
        - bogdandm/tests-online-frontend:unstable
        - bogdandm/tests-online-frontend:latest
      args:
        REACT_APP_DOMAIN: https://tests.bogdandm.xyz
