# TODO: Add health check

version: '3.7'

volumes:
  redis-data:
  pg-data:
  static-data:
  media-data:

services:
  nginx:
    image: tests-online-nginx:latest
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: unless-stopped
    volumes:
      - static-data:/srv/tests-online/static
      - media-data:/srv/tests-online/media
    ports:
      - "0.0.0.0:8000:80"
    links:
      - django
    depends_on:
      - django
    command: nginx -g "daemon off;"
    container_name: tests-online-nginx

  django:
    image: tests-online-django:latest
    build:
      context: ../
      dockerfile: ./tests_online_docker/django/Dockerfile
    restart: unless-stopped
    volumes:
      - static-data:/opt/tests_online/static
      - media-data:/opt/tests_online/media
      - ../logs:/opt/tests_online/logs
    working_dir: /opt/tests_online
    env_file:
      - ../.env
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    expose:
      - 2021
    #    command: tail -f /dev/null
    command: /bin/bash -c '/opt/tests_online/tests_online_docker/django/run_django.sh'
    container_name: tests-online-django

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - ../.env
    container_name: tests-online-db

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command: redis-server # --appendonly yes
    container_name: tests-online-redis