# Generated by Django 2.2 on 2019-04-30 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('position',), 'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('position',), 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
    ]
