# Generated by Django 2.2.1 on 2019-05-02 11:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('questions', '0005_auto_20190430_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ('id',), 'verbose_name': 'Test', 'verbose_name_plural': 'Tests'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='params_value',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0.0], size=None,
                                                            verbose_name='Parameters'),
            preserve_default=False,
        ),
    ]
