# Generated by Django 2.2.1 on 2019-05-13 16:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('questions', '0006_auto_20190502_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('position', 'pk'), 'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
    ]
